name: deploy-pr0nbot

on:
  schedule:
    - cron: '0 * * * *'
      name: Monitor
      jobs:
        - monitor
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }} 
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD}}
        script: |
          cd pr0nbot/
          git pull
          env GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o pr0nbot
          nohup bash -c "./pr0nbot -t $pronbotkey 2>&1 &" > pr0nbot.log

  monitor:
    runs-on: ubuntu-latest
    steps:
    - name: Check if program is running
      run: |
        pgrep pr0nbot
      continue-on-error: true
    - name: Restart program if it is not running
      if: failure()
      run: |
        nohup bash -c "./pr0nbot -t $pronbotkey 2>&1 &" > pr0nbot.log